# Generated by Django 6.0 on 2026-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='actual_days_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_estimated_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
